config/routes.rb
Rails.application.routes.draw do
  get 'payments/create'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }


  resources :products do
    resources :comments
  end
  resources :users
  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/index'

  get 'simple_pages/landing_page'

  root 'simple_pages#landing_page'

  post 'simple_pages/thank_you'

  post 'payments/create'

  get 'payments/success'
  resources :orders, only: [:index, :show, :create, :destroy]

  mount ActionCable.server => '/cable'
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superapp</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= csrf_meta_tags %>
  </head>

<body>
  <nav class="navbar navbar-fixed-top" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbarCollapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div><!--end navbar-header-->

    <p class="navbar-text"><span class="span-orange">Hobo <span class="span-blue">Nickel</span> <span class="span-nickel">Coins</span></p>

    <div class="collapse navbar-collapse navbarCollapse">
    <ul class="nav navbar-nav nav-space">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", simple_pages_about_path %></li>
      <li><%= link_to "Contact", simple_pages_contact_path %></li>
      <li><%= link_to "Products", products_path %></li>
    </ul>
<div  class = "nav navbar-nav navbar-right navblock-margin" >
  <ul>
      <li class="sidebar">
        <%= form_with(url: products_path, method: "get", local: true, class: "navbar-form navbar-right") do |form| %>
          <%= form.text_field :q, id: "q", value: params[:q], type: "text", class: "form-control", placeholder: "search Hobo Nickels" %>
          <%= submit_tag("Search", class: "btn btn-search", font: "fira sans") %>
        <% end %>
      </li>
        <% if user_signed_in? %>
           <li><%= link_to("logout", destroy_user_session_path, method: :delete)%></li>
        <% else %>
           <li><%= link_to("login", new_user_session_path)%></li>
        <% end %>
  </ul>
</div><!--end nav div-->
  </div><!--end container-fluid-->
  </div><!--end navbar collapse-->
</nav>
<!-- Flash Notice Tags -->
<div class="flashtags">
    <% if notice %>
      <div id="notice" class="alert alert-warning"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div id="alert" class="alert alert-danger"><%= alert %></div>
    <% end %>
</div>
    <br><br>
<%= yield %><!--spacing-->
<br><br><br><br>
<footer class="navbar-default navbar-fixed-bottom" style="background-color: #75DBCD;">
 <div class="container-fluid">
   <span class="text-muted" style="color: #6F2D2E;">&copy; 2018 Giles Lewey</span>
 </div><!--end container-fluid-->
</footer>



  </body>
</html>